version: "3.8"

services:
  db:
    image: mongo
    container_name: comm-db
    volumes: 
      - mongodata:/data/comm-db
    ports:
      - 27017:27017
    logging:
      driver: none

  job-queue:
    image: redis
    container_name: comm-redis
    ports:
      - 6379:6379

  backend:
    container_name: comm-backend
    build: ./backend
    volumes:
      - ./backend:/app
    #  - /node_modules:/backend/node_modules
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    container_name: comm-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
     # - /node_modules:/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true


volumes:
  mongodata: